baseurl = "https://dcompgriff.github.io/ML_OD_Benchmarking"
languageCode = "en-us"
title = "CS766 Project"
publishDir = "../"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
#themesDir = "../.."

# Set to true so images in markdown are prepended with base url.
canonifyurls = true


[params]
    site_author = "Dan Griffin"
    site_author2 = "Yudhister Satija"
    site_description = "CS766 Deep object detection benchmarking and sensitivity analysis."
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/dgriffin.jpg"
    avatar2 = "img/YudhisterSatija.jpg"
    header_background = "img/desk.jpg"
    header_title = "CS 766 Project: Deep Object Detection Network Analysis."
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "dcompgriff"
    gplus     = ""

[social2]
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "Yudhister"
    gplus     = ""
